/**
 * Plan-channel tests: the generation context, structural verification, and the
 * artifact write with its header, archive, and cache record.
 *
 * @module xl/tests/artifact
 */

import assert from 'node:assert/strict'
import { existsSync } from 'node:fs'
import test from 'node:test'
import { contextFor, emitArtifacts, verifyArtifacts } from '../src/core/artifact.js'
import { dropWorkspace, makeWorkspace, read } from './helpers.js'

const DEMO = [
  '# namespace demo',
  'demo package.',
  '',
  '# class point',
  '',
  '## field x:int = 0',
  'x.',
  '',
  '## method move:(dx:int)=>void',
  'move.',
  '```ts',
  'this.x = dx;',
  '```',
  '',
  '### csharp',
  '```csharp',
  'public void Move(int dx) { X += dx; }',
  '```',
  '',
].join('\n')

test('the generation context reports outputs, contract, and language sections', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const opened = contextFor({ cwd, source: 'demo.xl.md', target: 'csharp', env: {} })
    assert.deepEqual(opened.context.outputs.map(output => output.path), [
      'dist/csharp/Point.cs',
    ])
    assert.equal(opened.context.channel, 'harness')
    assert.equal(opened.context.summary.types[0].name, 'point')
    assert.equal(opened.context.summary.types[0].members[1].name, 'move')
    assert.equal(opened.context.language.namespace.name, 'demo')
    assert.ok(opened.context.language.sections.some(section => section.code.includes('Move')))
    assert.match(opened.context.promptHash, /^[0-9a-f]{16}$/)
    assert.equal(opened.context.previous, null)
  } finally {
    dropWorkspace(cwd)
  }
})

test('the context hash changes when the source structure changes', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const first = contextFor({ cwd, source: 'demo.xl.md', target: 'csharp', env: {} }).context.promptHash
    const changed = DEMO.replace('## field x:int = 0', '## field x:int = 1')
    const cwd2 = makeWorkspace({ 'demo.xl.md': changed })
    const second = contextFor({ cwd: cwd2, source: 'demo.xl.md', target: 'csharp', env: {} }).context.promptHash
    assert.notEqual(first, second)
    dropWorkspace(cwd2)
  } finally {
    dropWorkspace(cwd)
  }
})

test('verification passes for content that matches the contract', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const verdict = verifyArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'csharp',
      files: [{ path: 'dist/csharp/Point.cs', content: 'public class point { public int x; public void move(int dx) {} }' }],
      env: {},
    })
    assert.equal(verdict.ok, true)
    assert.deepEqual(verdict.planned, ['dist/csharp/Point.cs'])
  } finally {
    dropWorkspace(cwd)
  }
})

test('verification reports a member that is absent from the product', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const verdict = verifyArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'csharp',
      files: [{ path: 'dist/csharp/Point.cs', content: 'public class point { }' }],
      env: {},
    })
    assert.equal(verdict.ok, false)
    assert.ok(verdict.issues[0].issues.some(issue => issue.includes('move')))
  } finally {
    dropWorkspace(cwd)
  }
})

test('verification reports a parameter-count mismatch', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const verdict = verifyArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'csharp',
      files: [{ path: 'dist/csharp/Point.cs', content: 'public class point { public int x; public void move(int a, int b) {} }' }],
      env: {},
    })
    assert.equal(verdict.ok, false)
    assert.ok(verdict.issues[0].issues.some(issue => issue.includes('1 parameter')))
  } finally {
    dropWorkspace(cwd)
  }
})

test('emit writes the header, the fingerprint, the context hash, and the model', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = emitArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'csharp',
      model: 'deepseek-flash',
      files: [{ path: 'dist/csharp/Point.cs', content: 'public class point {\n  public int x;\n  public void move(int dx) {}\n}\n' }],
      env: {},
    })
    assert.equal(result.ok, true)
    assert.deepEqual(result.written, ['dist/csharp/Point.cs'])
    const artifact = read(cwd, 'dist/csharp/Point.cs')
    const lines = artifact.split('\n')
    assert.equal(lines[0], '// @generated by xl from demo.xl.md')
    assert.match(lines[1], /xl:sha256:[0-9a-f]{64} {2}xl:target:csharp {2}xl:ver:0\.1\.0 {2}xl:model:deepseek-flash {2}xl:prompt:[0-9a-f]{16}/)
    assert.equal(lines[3], '')
    assert.ok(artifact.endsWith('}\n'))
    assert.ok(existsSync(`${cwd}/dist/csharp/.xl/cache.json`))
  } finally {
    dropWorkspace(cwd)
  }
})

test('emit refuses a path that is not planned', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = emitArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'csharp',
      files: [{ path: 'elsewhere/Point.cs', content: 'public class point {}' }],
      env: {},
    })
    assert.equal(result.ok, false)
    assert.equal(result.written.length, 0)
    assert.ok(result.diagnostics.some(item => item.code === 'E2001'))
    assert.equal(existsSync(`${cwd}/elsewhere`), false)
  } finally {
    dropWorkspace(cwd)
  }
})

test('emit refuses to write a product that does not match the contract', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = emitArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'csharp',
      files: [{ path: 'dist/csharp/Point.cs', content: 'public class point { }' }],
      env: {},
    })
    assert.equal(result.ok, false)
    assert.ok(result.diagnostics.some(item => item.code === 'E4002'))
    assert.equal(existsSync(`${cwd}/dist/csharp/Point.cs`), false)
  } finally {
    dropWorkspace(cwd)
  }
})

test('the second emit archives the first version and the cache offers it back', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const first = 'public class point {\n  public int x;\n  public void move(int dx) {}\n}\n'
    emitArtifacts({ cwd, source: 'demo.xl.md', target: 'csharp', files: [{ path: 'dist/csharp/Point.cs', content: first }], env: {} })
    const archived = read(cwd, 'dist/csharp/Point.cs')
    const second = 'public class point {\n  public int x;\n  public void move(int dx) { X += dx; }\n}\n'
    emitArtifacts({ cwd, source: 'demo.xl.md', target: 'csharp', files: [{ path: 'dist/csharp/Point.cs', content: second }], env: {} })
    // The archive keeps the artifact xl wrote, header included, not the raw input.
    assert.equal(read(cwd, 'dist/csharp/.xl/cache/demo.cs.1'), archived)
    assert.ok(read(cwd, 'dist/csharp/Point.cs').includes('X += dx'))
    const opened = contextFor({ cwd, source: 'demo.xl.md', target: 'csharp', env: {} })
    assert.equal(opened.context.previous.version, 1)
    assert.ok(opened.context.previous.text.includes('public void move(int dx) {}'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('emit can skip verification when the caller asks', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = emitArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'csharp',
      options: { verify: false },
      files: [{ path: 'dist/csharp/Point.cs', content: 'public class point { }' }],
      env: {},
    })
    assert.equal(result.ok, true)
    assert.equal(existsSync(`${cwd}/dist/csharp/Point.cs`), true)
  } finally {
    dropWorkspace(cwd)
  }
})

test('a statement section is part of the contract and reaches the non-ts context', () => {
  const source = [
    '# namespace demo',
    'demo package.',
    '',
    '# class point',
    '',
    '## field x:int = 0',
    'x.',
    '',
    '# statement',
    'entry.',
    '```ts',
    'run();',
    '```',
    '',
    '## csharp',
    '```csharp',
    'Run();',
    '```',
    '',
  ].join('\n')
  const cwd = makeWorkspace({ 'demo.xl.md': source })
  try {
    const opened = contextFor({ cwd, source: 'demo.xl.md', target: 'csharp', env: {} })
    assert.deepEqual(opened.context.outputs.map(output => output.path), [
      'dist/csharp/DemoModule.cs',
      'dist/csharp/Point.cs',
    ])
    assert.deepEqual(opened.context.summary.statements, [{ index: 1, hasBody: true, sections: ['csharp'] }])
    assert.ok(opened.context.language.sections.some(
      section => section.owner === '# statement 1' && section.code === 'Run();',
    ))
    assert.match(opened.context.promptHash, /^[0-9a-f]{16}$/)
  } finally {
    dropWorkspace(cwd)
  }
})
