/**
 * Plan-channel tests: the generation context, structural verification, and the
 * artifact write with its header, archive, and cache record.
 *
 * @module xl/tests/artifact
 */

import assert from 'node:assert/strict'
import { existsSync } from 'node:fs'
import test from 'node:test'
import { contextFor, emitArtifacts, verifyArtifacts } from '../src/core/artifact.js'
import { dropWorkspace, makeWorkspace, read } from './helpers.js'

const DEMO = [
  '# namespace demo',
  'demo package.',
  '',
  '# class point',
  '',
  '## field x:int = 0',
  'x.',
  '',
  '## method move:(dx:int)=>void',
  'move.',
  '```ts',
  'this.x = dx;',
  '```',
  '',
  '### csharp',
  '```csharp',
  'public void Move(int dx) { X += dx; }',
  '```',
  '',
].join('\n')

test('the generation context reports outputs, contract, and language sections', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const opened = contextFor({ cwd, source: 'demo.xl.md', target: 'csharp', env: {} })
    assert.deepEqual(opened.context.outputs.map(output => output.path), [
      'dist/csharp/Point.cs',
    ])
    assert.equal(opened.context.channel, 'harness')
    assert.equal(opened.context.summary.types[0].name, 'point')
    assert.equal(opened.context.summary.types[0].members[1].name, 'move')
    assert.equal(opened.context.language.namespace.name, 'demo')
    assert.ok(opened.context.language.sections.some(section => section.code.includes('Move')))
    assert.match(opened.context.promptHash, /^[0-9a-f]{16}$/)
    assert.equal(opened.context.previous.length, 0)
  } finally {
    dropWorkspace(cwd)
  }
})

test('the context hash changes when the source structure changes', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const first = contextFor({ cwd, source: 'demo.xl.md', target: 'csharp', env: {} }).context.promptHash
    const changed = DEMO.replace('## field x:int = 0', '## field x:int = 1')
    const cwd2 = makeWorkspace({ 'demo.xl.md': changed })
    const second = contextFor({ cwd: cwd2, source: 'demo.xl.md', target: 'csharp', env: {} }).context.promptHash
    assert.notEqual(first, second)
    dropWorkspace(cwd2)
  } finally {
    dropWorkspace(cwd)
  }
})

test('verification passes for content that matches the contract', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const verdict = verifyArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'csharp',
      files: [{ path: 'dist/csharp/Point.cs', content: 'public class point { public int x; public void move(int dx) {} }' }],
      env: {},
    })
    assert.equal(verdict.ok, true)
    assert.deepEqual(verdict.planned, ['dist/csharp/Point.cs'])
  } finally {
    dropWorkspace(cwd)
  }
})

test('verification reports a member that is absent from the product', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const verdict = verifyArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'csharp',
      files: [{ path: 'dist/csharp/Point.cs', content: 'public class point { }' }],
      env: {},
    })
    assert.equal(verdict.ok, false)
    assert.ok(verdict.issues[0].issues.some(issue => issue.includes('move')))
  } finally {
    dropWorkspace(cwd)
  }
})

test('verification reports a parameter-count mismatch', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const verdict = verifyArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'csharp',
      files: [{ path: 'dist/csharp/Point.cs', content: 'public class point { public int x; public void move(int a, int b) {} }' }],
      env: {},
    })
    assert.equal(verdict.ok, false)
    assert.ok(verdict.issues[0].issues.some(issue => issue.includes('1 parameter')))
  } finally {
    dropWorkspace(cwd)
  }
})

test('emit writes the header, the fingerprint, the context hash, and the model', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = emitArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'csharp',
      model: 'deepseek-flash',
      files: [{ path: 'dist/csharp/Point.cs', content: 'public class point {\n  public int x;\n  public void move(int dx) {}\n}\n' }],
      env: {},
    })
    assert.equal(result.ok, true)
    assert.deepEqual(result.written, ['dist/csharp/Point.cs'])
    const artifact = read(cwd, 'dist/csharp/Point.cs')
    const lines = artifact.split('\n')
    assert.equal(lines[0], '// @generated by xl from demo.xl.md')
    assert.match(lines[1], /xl:sha256:[0-9a-f]{64} {2}xl:target:csharp {2}xl:ver:0\.1\.0 {2}xl:model:deepseek-flash {2}xl:prompt:[0-9a-f]{16}/)
    assert.equal(lines[3], '')
    assert.ok(artifact.endsWith('}\n'))
    assert.ok(existsSync(`${cwd}/dist/csharp/.xl/cache.json`))
  } finally {
    dropWorkspace(cwd)
  }
})

test('emit refuses a path that is not planned', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = emitArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'csharp',
      files: [{ path: 'elsewhere/Point.cs', content: 'public class point {}' }],
      env: {},
    })
    assert.equal(result.ok, false)
    assert.equal(result.written.length, 0)
    assert.ok(result.diagnostics.some(item => item.code === 'E2001'))
    assert.equal(existsSync(`${cwd}/elsewhere`), false)
  } finally {
    dropWorkspace(cwd)
  }
})

test('emit refuses to write a product that does not match the contract', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = emitArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'csharp',
      files: [{ path: 'dist/csharp/Point.cs', content: 'public class point { }' }],
      env: {},
    })
    assert.equal(result.ok, false)
    assert.ok(result.diagnostics.some(item => item.code === 'E4002'))
    assert.equal(existsSync(`${cwd}/dist/csharp/Point.cs`), false)
  } finally {
    dropWorkspace(cwd)
  }
})

const CPP_DEMO = [
  '# class point',
  '',
  '## field x:int = 0',
  'x.',
  '',
  '## method move:(dx:int)=>void',
  'move.',
  '```ts',
  'this.x = dx;',
  '```',
  '',
].join('\n')

const CPP_HEADER = [
  '#pragma once',
  '',
  'class point {',
  'public:',
  '  int x = 0;',
  '  void move(int dx);',
  '};',
  '',
].join('\n')

const CPP_SOURCE = [
  '#include "point.h"',
  '',
  'void point::move(int dx) {',
  '  x += dx;',
  '}',
  '',
].join('\n')

test('a two-part target plans both parts and refuses a partial submission', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': CPP_DEMO })
  try {
    const opened = contextFor({ cwd, source: 'demo.xl.md', target: 'cpp', env: {} })
    assert.deepEqual(opened.context.outputs.map(output => [output.path, output.part, output.scope]), [
      ['dist/cpp/point.h', 'header', 'declaration'],
      ['dist/cpp/point.cpp', 'source', 'definition'],
    ])
    assert.deepEqual(opened.context.parts.map(part => part.role), ['header', 'source'])

    const partial = verifyArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'cpp',
      files: [{ path: 'dist/cpp/point.h', content: CPP_HEADER }],
      env: {},
    })
    assert.equal(partial.ok, false)
    assert.ok(partial.issues.some(entry => entry.path === 'dist/cpp/point.cpp'))

    const full = verifyArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'cpp',
      files: [
        { path: 'dist/cpp/point.h', content: CPP_HEADER },
        { path: 'dist/cpp/point.cpp', content: CPP_SOURCE },
      ],
      env: {},
    })
    assert.equal(full.ok, true)
  } finally {
    dropWorkspace(cwd)
  }
})

test('the definition part is checked for the type it mentions, not for every member', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': CPP_DEMO })
  try {
    // A definition that only implements `move` is correct C++: `x` is declared
    // in the header. Demanding every member here would reject it.
    const verdict = verifyArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'cpp',
      files: [
        { path: 'dist/cpp/point.h', content: CPP_HEADER },
        { path: 'dist/cpp/point.cpp', content: 'void point::move(int dx) {\n}\n' },
      ],
      env: {},
    })
    assert.equal(verdict.ok, true)
    // A definition that names nothing of the type is still refused.
    const empty = verifyArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'cpp',
      files: [
        { path: 'dist/cpp/point.h', content: CPP_HEADER },
        { path: 'dist/cpp/point.cpp', content: '// nothing here\n' },
      ],
      env: {},
    })
    assert.equal(empty.ok, false)
    assert.ok(empty.issues[0].issues.some(issue => issue.includes('point')))
  } finally {
    dropWorkspace(cwd)
  }
})

test('cpp emit writes both parts with their own header and archives each extension', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': CPP_DEMO })
  try {
    const files = (source) => [
      { path: 'dist/cpp/point.h', content: CPP_HEADER },
      { path: 'dist/cpp/point.cpp', content: source },
    ]
    const first = emitArtifacts({ cwd, source: 'demo.xl.md', target: 'cpp', files: files(CPP_SOURCE), env: {} })
    assert.equal(first.ok, true)
    assert.deepEqual(first.written, ['dist/cpp/point.h', 'dist/cpp/point.cpp'])
    assert.ok(read(cwd, 'dist/cpp/point.h').startsWith('// @generated by xl from demo.xl.md'))
    assert.ok(read(cwd, 'dist/cpp/point.cpp').startsWith('// @generated by xl from demo.xl.md'))

    const second = emitArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'cpp',
      files: files('void point::move(int dx) {\n  x += dx * 2;\n}\n'),
      env: {},
    })
    assert.equal(second.ok, true)
    // Each part keeps its own archive family.
    assert.ok(existsSync(`${cwd}/dist/cpp/.xl/cache/demo.h.1`))
    assert.ok(existsSync(`${cwd}/dist/cpp/.xl/cache/demo.cpp.1`))

    const opened = contextFor({ cwd, source: 'demo.xl.md', target: 'cpp', env: {} })
    assert.deepEqual(opened.context.previous.map(item => [item.part, item.ext, item.version]), [
      ['header', '.h', 1],
      ['source', '.cpp', 1],
    ])
    // The pointer is named the way every other planned path is: POSIX and
    // relative to the working directory.
    assert.deepEqual(opened.context.previous.map(item => item.path), [
      'dist/cpp/.xl/cache/demo.h.1',
      'dist/cpp/.xl/cache/demo.cpp.1',
    ])
    assert.ok(opened.context.previous[0].text.includes('void move(int dx);'))
    assert.ok(opened.context.previous[1].text.includes('x += dx;'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('the context hash covers the target parts', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': CPP_DEMO })
  try {
    const cpp = contextFor({ cwd, source: 'demo.xl.md', target: 'cpp', env: {} }).context.promptHash
    const csharp = contextFor({ cwd, source: 'demo.xl.md', target: 'csharp', env: {} }).context.promptHash
    assert.notEqual(cpp, csharp)
    // A declared target whose parts differ plans different files, so its hash
    // must differ too, even though layout and source are identical.
    const single = contextFor({
      cwd,
      source: 'demo.xl.md',
      target: 'cpp2',
      env: {},
      config: { targets: { cpp2: { ext: '.h' } } },
    }).context.promptHash
    assert.notEqual(cpp, single)
  } finally {
    dropWorkspace(cwd)
  }
})

test('the second emit archives the first version and the cache offers it back', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const first = 'public class point {\n  public int x;\n  public void move(int dx) {}\n}\n'
    emitArtifacts({ cwd, source: 'demo.xl.md', target: 'csharp', files: [{ path: 'dist/csharp/Point.cs', content: first }], env: {} })
    const archived = read(cwd, 'dist/csharp/Point.cs')
    const second = 'public class point {\n  public int x;\n  public void move(int dx) { X += dx; }\n}\n'
    emitArtifacts({ cwd, source: 'demo.xl.md', target: 'csharp', files: [{ path: 'dist/csharp/Point.cs', content: second }], env: {} })
    // The archive keeps the artifact xl wrote, header included, not the raw input.
    assert.equal(read(cwd, 'dist/csharp/.xl/cache/demo.cs.1'), archived)
    assert.ok(read(cwd, 'dist/csharp/Point.cs').includes('X += dx'))
    const opened = contextFor({ cwd, source: 'demo.xl.md', target: 'csharp', env: {} })
    assert.deepEqual(opened.context.previous.map(item => [item.part, item.ext, item.version]), [['file', '.cs', 1]])
    assert.ok(opened.context.previous[0].text.includes('public void move(int dx) {}'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('emit can skip verification when the caller asks', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = emitArtifacts({
      cwd,
      source: 'demo.xl.md',
      target: 'csharp',
      options: { verify: false },
      files: [{ path: 'dist/csharp/Point.cs', content: 'public class point { }' }],
      env: {},
    })
    assert.equal(result.ok, true)
    assert.equal(existsSync(`${cwd}/dist/csharp/Point.cs`), true)
  } finally {
    dropWorkspace(cwd)
  }
})

test('a statement section is part of the contract and reaches the non-ts context', () => {
  const source = [
    '# namespace demo',
    'demo package.',
    '',
    '# class point',
    '',
    '## field x:int = 0',
    'x.',
    '',
    '# statement',
    'entry.',
    '```ts',
    'run();',
    '```',
    '',
    '## csharp',
    '```csharp',
    'Run();',
    '```',
    '',
  ].join('\n')
  const cwd = makeWorkspace({ 'demo.xl.md': source })
  try {
    const opened = contextFor({ cwd, source: 'demo.xl.md', target: 'csharp', env: {} })
    assert.deepEqual(opened.context.outputs.map(output => output.path), [
      'dist/csharp/DemoModule.cs',
      'dist/csharp/Point.cs',
    ])
    assert.deepEqual(opened.context.summary.statements, [{ index: 1, hasBody: true, sections: ['csharp'] }])
    assert.ok(opened.context.language.sections.some(
      section => section.owner === '# statement 1' && section.code === 'Run();',
    ))
    assert.match(opened.context.promptHash, /^[0-9a-f]{16}$/)
  } finally {
    dropWorkspace(cwd)
  }
})
