/**
 * Build tests: the ts channel writes, the plan channel does not, and the cache
 * and conflict rules hold.
 *
 * @module xl/tests/build
 */

import assert from 'node:assert/strict'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'
import { runBuild, runCheck, runPlan } from '../src/core/build.js'
import { dropWorkspace, makeWorkspace, read, writeFiles } from './helpers.js'

const DEMO = [
  '# method greet:(name:string)=>string',
  'greet.',
  '```ts',
  'return `hi ${name}`;',
  '```',
  '',
  '# class point',
  '',
  '## field x:int = 0',
  'x.',
  '',
].join('\n')

test('the ts channel writes an artifact with the header and records the cache', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'] }, env: {} })
    assert.equal(result.exitCode, 0)
    assert.equal(result.written, 1)
    const artifact = read(cwd, 'demo.ts')
    const lines = artifact.split('\n')
    assert.equal(lines[0], '// @generated by xl from demo.xl.md')
    assert.match(lines[1], /^\/\/ xl:sha256:[0-9a-f]{64} {2}xl:target:ts {2}xl:ver:0\.1\.0$/)
    assert.equal(lines[2], '// DO NOT EDIT — 修改请改 xl.md 并重新生成')
    assert.equal(lines[3], '')
    assert.ok(artifact.endsWith('}\n'))
    assert.ok(existsSync(join(cwd, '.xl', 'cache.json')))
  } finally {
    dropWorkspace(cwd)
  }
})

test('a second run with an unchanged source is skipped', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'] }, env: {} })
    const second = runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'] }, env: {} })
    assert.equal(second.skipped, 1)
    assert.equal(second.written, 0)
  } finally {
    dropWorkspace(cwd)
  }
})

test('--force regenerates and --no-cache leaves no cache file', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'], force: true, cache: false }, env: {} })
    assert.equal(existsSync(join(cwd, '.xl', 'cache.json')), false)
  } finally {
    dropWorkspace(cwd)
  }
})

test('a changed source overwrites the artifact and archives the previous version', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'] }, env: {} })
    const first = read(cwd, 'demo.ts')
    const changed = DEMO.replace('hi ${name}', 'hello ${name}')
    writeFiles(cwd, { 'demo.xl.md': changed })
    const second = runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'] }, env: {} })
    assert.equal(second.written, 1)
    assert.notEqual(read(cwd, 'demo.ts'), first)
    assert.equal(read(cwd, '.xl/cache/demo.ts.1'), first)
  } finally {
    dropWorkspace(cwd)
  }
})

test('a non-ts target is planned only and writes nothing', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['csharp'] }, env: {} })
    assert.equal(result.exitCode, 0)
    assert.equal(result.written, 0)
    assert.equal(result.planned, 1)
    assert.equal(existsSync(join(cwd, 'csharp')), false)
    assert.equal(result.files[0].status, 'planned')
    assert.deepEqual(result.files[0].out, ['csharp/DemoModule.cs', 'csharp/Point.cs'])
  } finally {
    dropWorkspace(cwd)
  }
})

test('an output that is not an xl artifact is a conflict without --force', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO, 'demo.ts': 'hand written\n' })
  try {
    const result = runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'] }, env: {} })
    assert.equal(result.exitCode, 1)
    assert.ok(result.diagnostics.some(item => item.code === 'E2001'))
    assert.equal(read(cwd, 'demo.ts'), 'hand written\n')
  } finally {
    dropWorkspace(cwd)
  }
})

test('--force overwrites a foreign file at the planned path', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO, 'demo.ts': 'hand written\n' })
  try {
    const result = runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'], force: true }, env: {} })
    assert.equal(result.exitCode, 0)
    assert.ok(read(cwd, 'demo.ts').startsWith('// @generated by xl'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('--dry-run reports the plan without writing', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'], dryRun: true }, env: {} })
    assert.equal(result.written, 0)
    assert.equal(existsSync(join(cwd, 'demo.ts')), false)
    assert.equal(result.files[0].status, 'planned')
  } finally {
    dropWorkspace(cwd)
  }
})

test('--stdout writes the artifact to the result instead of the disk', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'], stdout: true }, env: {} })
    assert.equal(result.stdout.length, 1)
    assert.equal(existsSync(join(cwd, 'demo.ts')), false)
  } finally {
    dropWorkspace(cwd)
  }
})

test('a source error stops the build with exit code 1', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': '# struct point\n' })
  try {
    const result = runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'] }, env: {} })
    assert.equal(result.exitCode, 1)
    assert.ok(result.diagnostics.some(item => item.code === 'E1002'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('a missing dependency target is E1006', () => {
  const source = [
    '# dependencies',
    '```xl',
    'import { level } from "./missing.xl.md"',
    '```',
    '',
    '# class point',
    '',
    '## field x:int = 0',
    'x.',
    '',
  ].join('\n')
  const cwd = makeWorkspace({ 'demo.xl.md': source })
  try {
    const result = runCheck({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'] }, env: {} })
    assert.equal(result.exitCode, 1)
    assert.ok(result.diagnostics.some(item => item.code === 'E1006'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('a resolved dependency is not reported', () => {
  const source = [
    '# dependencies',
    '```xl',
    'import { level } from "./util.xl.md"',
    '```',
    '',
    '# class point',
    '',
    '## field x:level = level.info',
    'x.',
    '',
  ].join('\n')
  const util = ['# enum level', '- case info', ''].join('\n')
  const cwd = makeWorkspace({ 'demo.xl.md': source, 'util.xl.md': util })
  try {
    const result = runCheck({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'] }, env: {} })
    assert.equal(result.diagnostics.some(item => item.code === 'E1006'), false)
  } finally {
    dropWorkspace(cwd)
  }
})

test('a ts source with a dependent package builds both files', () => {
  const util = ['# enum level', '- case info', ''].join('\n')
  const demo = [
    '# dependencies',
    '```xl',
    'import { level } from "./util.xl.md"',
    '```',
    '',
    '# class point',
    '',
    '## field x:level = level.info',
    'x.',
    '',
  ].join('\n')
  const cwd = makeWorkspace({ 'demo.xl.md': demo, 'util.xl.md': util })
  try {
    const result = runBuild({ cwd, paths: ['.'], cli: { targets: ['ts'], out: 'dist' }, env: {} })
    assert.equal(result.exitCode, 0)
    assert.equal(result.written, 2)
    assert.ok(read(cwd, 'dist/demo.ts').includes('import { level } from "./util";'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('the plan reports cache reuse and the previous version pointer', () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'] }, env: {} })
    const plan = runPlan({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'] }, env: {} })
    assert.equal(plan.plans[0].reuse.reusable, true)
    assert.deepEqual(plan.plans[0].outputs.map(output => output.path), ['demo.ts'])
  } finally {
    dropWorkspace(cwd)
  }
})

test('xl.json supplies the default target and output root', () => {
  const config = JSON.stringify({ build: { target: ['csharp'], out: 'gen' } })
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO, 'xl.json': config })
  try {
    const result = runBuild({ cwd, paths: ['demo.xl.md'], cli: {}, env: {} })
    assert.deepEqual(result.targets, ['csharp'])
    assert.equal(result.files[0].out[0], 'gen/csharp/DemoModule.cs')
  } finally {
    dropWorkspace(cwd)
  }
})

test('the CLI target list outranks the configuration file', () => {
  const config = JSON.stringify({ build: { target: ['csharp'] } })
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO, 'xl.json': config })
  try {
    const result = runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['ts'] }, env: {} })
    assert.deepEqual(result.targets, ['ts'])
    assert.equal(result.written, 1)
  } finally {
    dropWorkspace(cwd)
  }
})

test('an environment target override beats the configuration file and loses to the CLI', () => {
  const config = JSON.stringify({ build: { target: ['csharp'] } })
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO, 'xl.json': config })
  try {
    const fromEnv = runBuild({ cwd, paths: ['demo.xl.md'], cli: {}, env: { XL_TARGET: 'ts' } })
    assert.deepEqual(fromEnv.targets, ['ts'])
    const fromCli = runBuild({ cwd, paths: ['demo.xl.md'], cli: { targets: ['python'] }, env: { XL_TARGET: 'ts' } })
    assert.deepEqual(fromCli.targets, ['python'])
  } finally {
    dropWorkspace(cwd)
  }
})
