/**
 * `xl` command-line tests: argument parsing and a full invocation through the
 * application row.
 *
 * @module xl/tests/cli
 */

import assert from 'node:assert/strict'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'
import { apply, internals, name, inject } from '../src/plugin/cli.js'
import { createXlService } from '../src/plugin/service.js'
import { parseArgs, validateOptions } from '../src/plugin/args.js'
import { dropWorkspace, makeWorkspace, read } from './helpers.js'

const DEMO = [
  '# class point',
  '',
  '## field x:int = 0',
  'x.',
  '',
].join('\n')

test('the application row declares what it needs', () => {
  assert.equal(name, 'xl-cli')
  assert.deepEqual(inject, ['cmdlineArgs', 'xl'])
})

test('parseArgs separates the command, the paths, and the options', () => {
  const parsed = parseArgs(['build', 'src', '--target', 'ts', '-t', 'csharp', '-o', 'dist', '--flat', 'pkg'])
  assert.equal(parsed.command, 'build')
  assert.deepEqual(parsed.paths, ['src', 'pkg'])
  assert.deepEqual(parsed.options.targets, ['ts', 'csharp'])
  assert.equal(parsed.options.out, 'dist')
  assert.equal(parsed.options.flat, true)
  assert.deepEqual(parsed.errors, [])
})

test('parseArgs accepts --name=value and short flags', () => {
  const parsed = parseArgs(['check', '--format=compact', '-q', '--ignore', 'W3102,W3011'])
  assert.equal(parsed.command, 'check')
  assert.equal(parsed.options.format, 'compact')
  assert.equal(parsed.options.quiet, true)
  assert.deepEqual(parsed.options.ignore, ['W3102', 'W3011'])
})

test('parseArgs stops option scanning at --', () => {
  const parsed = parseArgs(['build', '--', '--flat'])
  assert.deepEqual(parsed.paths, ['--flat'])
  assert.equal(parsed.options.flat, undefined)
})

test('parseArgs reports an unknown command, option, and missing value', () => {
  assert.equal(parseArgs(['deploy']).errors[0], 'unknown command "deploy"')
  assert.ok(parseArgs(['build', '--nope']).errors.some(message => message.includes('--nope')))
  assert.ok(parseArgs(['build', '--out']).errors.some(message => message.includes('requires a value')))
})

test('parseArgs rejects a value on a boolean flag', () => {
  assert.ok(parseArgs(['build', '--flat=yes']).errors.some(message => message.includes('takes no value')))
})

test('parseArgs rejects a non-numeric numeric option', () => {
  assert.ok(parseArgs(['build', '--concurrency', 'many']).errors.some(message => message.includes('requires a number')))
})

test('validateOptions rejects a closed value outside its set', () => {
  assert.equal(validateOptions({ layout: 'file' }).length, 0)
  assert.equal(validateOptions({ layout: 'grid' }).length, 1)
  assert.equal(validateOptions({ naming: 'kebab' }).length, 1)
  assert.equal(validateOptions({ format: 'xml' }).length, 1)
  assert.equal(validateOptions({ color: 'rainbow' }).length, 1)
})

/**
 * Run the CLI row against a fake context.
 * @param {readonly string[]} argv - the invocation's inner arguments.
 * @param {string} cwd - workspace root.
 * @returns {Promise<{code: number, stdout: string, stderr: string}>} the run outcome.
 */
async function runCli(argv, cwd) {
  const stdout = []
  const stderr = []
  const previous = { stdout: internals.stdout, stderr: internals.stderr }
  internals.stdout = { write: chunk => stdout.push(chunk) }
  internals.stderr = { write: chunk => stderr.push(chunk) }
  let resolveExit
  const exited = new Promise((resolve) => { resolveExit = resolve })
  const services = new Map([
    ['xl', createXlService({ workspaceRoot: cwd })],
    ['cmdlineArgs', { get: () => argv }],
    ['appExit', code => resolveExit(code)],
  ])
  const ctx = { get: serviceName => services.get(serviceName) }
  try {
    apply(ctx)
    const code = await exited
    return { code, stdout: stdout.join(''), stderr: stderr.join('') }
  } finally {
    internals.stdout = previous.stdout
    internals.stderr = previous.stderr
  }
}

test('xl build -t ts writes the artifact and exits 0', async () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = await runCli(['build', '-t', 'ts'], cwd)
    assert.equal(result.code, 0)
    assert.ok(read(cwd, 'dist/ts/demo.ts').startsWith('// @generated by xl'))
    assert.ok(result.stdout.includes('build done'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('xl build -t ts runs a # statement after the declarations, unexported', async () => {
  const source = [
    '# method Main:(args:Array<string>)=>void',
    '入口。',
    '```ts',
    'console.log(args);',
    '```',
    '',
    '# statement',
    '进程入口：模块被 import 时执行一次。',
    '```ts',
    'Main(process.argv.slice(2));',
    '```',
    '',
  ].join('\n')
  const cwd = makeWorkspace({ 'demo.xl.md': source })
  try {
    const result = await runCli(['build', '-t', 'ts'], cwd)
    assert.equal(result.code, 0)
    const artifact = read(cwd, 'dist/ts/demo.ts')
    assert.ok(artifact.startsWith('// @generated by xl'))
    assert.ok(artifact.includes('export function Main(args: string[]): void {'))
    // The statement is the last segment, carries no export, and keeps its prose out.
    assert.ok(artifact.endsWith('Main(process.argv.slice(2));\n'))
    assert.ok(!artifact.includes('export Main(process.argv'))
    assert.ok(!artifact.includes('进程入口'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('xl check reports W3013 for a static import inside # statement', async () => {
  const source = [
    '# statement',
    '```ts',
    'import fs from "node:fs";',
    'fs.readFileSync("x");',
    '```',
    '',
  ].join('\n')
  const cwd = makeWorkspace({ 'demo.xl.md': source })
  try {
    const result = await runCli(['check'], cwd)
    assert.equal(result.code, 0)
    // Diagnostics go to stderr; the summary line goes to stdout.
    assert.ok(result.stderr.includes('W3013'))
    assert.ok(result.stdout.includes('0 error(s), 1 warning(s)'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('xl build -t csharp plans only and says who generates it', async () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = await runCli(['build', '-t', 'csharp'], cwd)
    assert.equal(result.code, 0)
    assert.equal(existsSync(join(cwd, 'dist', 'csharp')), false)
    assert.ok(result.stdout.includes('xl_context'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('xl build --json writes an NDJSON event stream', async () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = await runCli(['build', '-t', 'ts', '--json'], cwd)
    const events = result.stdout.trim().split('\n').map(line => JSON.parse(line))
    assert.deepEqual(events.map(event => event.ev), ['build.start', 'file.plan', 'file.done', 'build.end'])
    assert.equal(events[3].written, 1)
  } finally {
    dropWorkspace(cwd)
  }
})

test('xl build --dry-run writes nothing', async () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = await runCli(['build', '-t', 'ts', '--dry-run'], cwd)
    assert.equal(result.code, 0)
    assert.equal(existsSync(join(cwd, 'dist', 'ts', 'demo.ts')), false)
  } finally {
    dropWorkspace(cwd)
  }
})

test('xl check reports diagnostics and exits 1 on an error', async () => {
  const cwd = makeWorkspace({ 'demo.xl.md': '# struct point\n' })
  try {
    const result = await runCli(['check'], cwd)
    assert.equal(result.code, 1)
    assert.ok(result.stderr.includes('E1002'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('xl check --strict turns a warning into a failure', async () => {
  const source = ['# class point', '', '## field x:int = 0', ''].join('\n')
  const cwd = makeWorkspace({ 'demo.xl.md': source })
  try {
    const lenient = await runCli(['check'], cwd)
    assert.equal(lenient.code, 0)
    const strict = await runCli(['check', '--strict'], cwd)
    assert.equal(strict.code, 1)
  } finally {
    dropWorkspace(cwd)
  }
})

test('xl targets lists the built-in targets', async () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = await runCli(['targets'], cwd)
    assert.equal(result.code, 0)
    assert.ok(result.stdout.includes('ts\tdirect\t.ts\tfile'))
    assert.ok(result.stdout.includes('csharp\tplan\t.cs\ttype'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('xl --help prints the usage text and exits 0', async () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = await runCli(['--help'], cwd)
    assert.equal(result.code, 0)
    assert.ok(result.stdout.includes('xl build [paths...] [options]'))
    assert.ok(result.stdout.includes('计划通道'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('xl --version prints the version', async () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = await runCli(['--version'], cwd)
    assert.equal(result.code, 0)
    assert.match(result.stdout.trim(), /^\d+\.\d+\.\d+$/)
  } finally {
    dropWorkspace(cwd)
  }
})

test('a bare xl invocation is a usage error', async () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = await runCli([], cwd)
    assert.equal(result.code, 2)
    assert.ok(result.stderr.includes('usage: xl'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('an unknown option is a usage error before any work happens', async () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = await runCli(['build', '--nope'], cwd)
    assert.equal(result.code, 2)
    assert.ok(result.stderr.includes('unknown option'))
    assert.equal(existsSync(join(cwd, 'dist', 'ts', 'demo.ts')), false)
  } finally {
    dropWorkspace(cwd)
  }
})

test('a missing input path is a usage error', async () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = await runCli(['build', 'nowhere'], cwd)
    assert.equal(result.code, 2)
    assert.ok(result.stderr.includes('does not exist'))
  } finally {
    dropWorkspace(cwd)
  }
})

test('xl build --stdout writes the artifact body to stdout', async () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const result = await runCli(['build', '-t', 'ts', '--stdout', '-q'], cwd)
    assert.equal(result.code, 0)
    assert.ok(result.stdout.includes('// @generated by xl'))
    assert.equal(existsSync(join(cwd, 'dist', 'ts', 'demo.ts')), false)
  } finally {
    dropWorkspace(cwd)
  }
})

test('a harness-era option is accepted and reported as unused under --verbose', async () => {
  const cwd = makeWorkspace({ 'demo.xl.md': DEMO })
  try {
    const quiet = await runCli(['build', '-t', 'ts'], cwd)
    assert.equal(quiet.stderr, '')
    dropWorkspace(cwd)
    const cwd2 = makeWorkspace({ 'demo.xl.md': DEMO })
    const verbose = await runCli(['build', '-t', 'ts', '--verbose', '--harness', 'dsh'], cwd2)
    assert.equal(verbose.code, 0)
    assert.ok(verbose.stderr.includes('--harness accepted but unused'))
    dropWorkspace(cwd2)
  } finally {
    dropWorkspace(cwd)
  }
})
