/**
 * The artifact header: the three-line `@generated` marker xl writes at the top
 * of every product, its tolerant parser, and the source fingerprint that makes
 * the incremental rule decidable.
 *
 * The header is the only contract between two xl runs, so its byte form
 * matters: three comment-prefixed lines, then one blank line, then the body.
 *
 * @module dsh-xl/core/header
 */

import { HEADER_MARK, normalizeNewlines, sha256 } from './text.js'

/** Comment markers the parser accepts, one per target-language family. */
const MARKER_PATTERN = '(?://|#|--|;)'

/** Line 1: `// @generated by xl from pkg/demo.xl.md`. */
const FIRST_LINE = new RegExp(`^\\s*${MARKER_PATTERN}\\s*${HEADER_MARK} from (.+?)\\s*$`)

/** Lines 2..3: any `xl:<field>:<value>` tokens on one comment line. */
const FIELDS_LINE = new RegExp(`^\\s*${MARKER_PATTERN}\\s*(xl:.*?)\\s*$`)

/**
 * Render the artifact header (xl-cli §3.6, xl-emit-ts §2).
 * @param {object} fields - header facts.
 * @param {string} fields.sourcePath - source path relative to the invocation cwd.
 * @param {string} fields.fingerprint - `sha256` of the normalized source bytes.
 * @param {string} fields.target - target language name.
 * @param {string} fields.version - xl version stamped into `xl:ver`.
 * @param {string} fields.comment - line-comment marker for the target language.
 * @param {string} [fields.model] - model id, recorded on the non-ts channel.
 * @param {string} [fields.promptHash] - generation-context hash, recorded on the non-ts channel.
 * @returns {string} the three header lines, without a trailing newline.
 */
export function renderHeader(fields) {
  const tokens = [
    `xl:sha256:${fields.fingerprint}`,
    `xl:target:${fields.target}`,
    `xl:ver:${fields.version}`,
  ]
  if (fields.model !== undefined && fields.model !== '') tokens.push(`xl:model:${fields.model}`)
  if (fields.promptHash !== undefined && fields.promptHash !== '') tokens.push(`xl:prompt:${fields.promptHash}`)
  return [
    `${fields.comment} ${HEADER_MARK} from ${fields.sourcePath}`,
    `${fields.comment} ${tokens.join('  ')}`,
    `${fields.comment} DO NOT EDIT — 修改请改 xl.md 并重新生成`,
  ].join('\n')
}

/**
 * Parse an artifact header. Returns `null` when the text does not start with
 * one, which is how a hand-written file is told apart from a product.
 * @param {string} text - the file's decoded text.
 * @returns {object | null} parsed header facts, or `null`.
 */
export function parseArtifactHeader(text) {
  const lines = normalizeNewlines(text).split('\n').slice(0, 3)
  const first = FIRST_LINE.exec(lines[0] ?? '')
  if (first === null) return null
  const header = {
    sourcePath: first[1],
    sha256: '',
    target: '',
    version: '',
    model: undefined,
    promptHash: undefined,
  }
  for (const line of lines.slice(1)) {
    const match = FIELDS_LINE.exec(line)
    if (match === null) continue
    for (const token of match[1].split(/\s{2,}/)) {
      const separator = token.lastIndexOf(':')
      if (separator <= 0) continue
      const key = token.slice(0, separator)
      const value = token.slice(separator + 1)
      if (key === 'xl:sha256') header.sha256 = value
      else if (key === 'xl:target') header.target = value
      else if (key === 'xl:ver') header.version = value
      else if (key === 'xl:model') header.model = value
      else if (key === 'xl:prompt') header.promptHash = value
    }
  }
  return header
}

/**
 * Whether a file's first line identifies it as an xl product. Products are
 * never scan inputs (xl-cli §3.2).
 * @param {string} text - the file's decoded text.
 * @returns {boolean} whether the file is an artifact.
 */
export function isArtifact(text) {
  const firstLine = normalizeNewlines(text).split('\n', 1)[0] ?? ''
  return firstLine.includes(HEADER_MARK)
}

/**
 * Fingerprint of a source file: `sha256` over its normalized bytes, so a
 * line-ending change alone never invalidates an artifact.
 * @param {string} text - the file's decoded text.
 * @returns {string} lowercase hex digest.
 */
export function fingerprintSource(text) {
  return sha256(normalizeNewlines(text))
}

/**
 * Fingerprint of a produced file's contents, used by the cache to detect a
 * hand-edited artifact (`E2003`).
 * @param {string} text - the artifact's decoded text.
 * @returns {string} lowercase hex digest.
 */
export function fingerprintArtifact(text) {
  return sha256(normalizeNewlines(text))
}

/**
 * Fingerprint of the generation context handed to a non-ts channel. A change
 * to the context invalidates the cached product even when the source is
 * unchanged (xl-cli §3.6).
 * @param {string} text - the assembled generation context.
 * @returns {string} lowercase hex digest, truncated to 16 characters.
 */
export function fingerprintPrompt(text) {
  return sha256(text).slice(0, 16)
}
