/**
 * Text, hashing, identifier, and code-block primitives shared by the parser,
 * the checker, and the ts printer. Every function here is pure.
 *
 * @module dsh-xl/core/text
 */

import { createHash } from 'node:crypto'

/** Two-space indentation unit of the ts printer (xl-emit-ts §11). */
export const INDENT = '  '

/** The artifact's first-line marker; its presence excludes a file from scan inputs. */
export const HEADER_MARK = '@generated by xl'

/** The one fence language that supplies a default-language (ts) block. */
export const DEFAULT_LANG = 'ts'

/**
 * Normalize every line ending to LF. A lone CR is normalized too, so a classic
 * Mac file cannot smuggle a carriage return into an artifact.
 * @param {string} text - input text.
 * @returns {string} text with LF line endings only.
 */
export function normalizeNewlines(text) {
  return text.replace(/\r\n?/g, '\n')
}

/**
 * Convert Windows separators to POSIX. Every path xl prints or stores uses
 * POSIX separators so output is comparable across platforms.
 * @param {string} value - path text.
 * @returns {string} the path with `/` separators.
 */
export function toPosix(value) {
  return value.replace(/\\/g, '/')
}

/**
 * Hex SHA-256 of a string's UTF-8 bytes.
 * @param {string} text - input text.
 * @returns {string} lowercase hex digest.
 */
export function sha256(text) {
  return createHash('sha256').update(text, 'utf8').digest('hex')
}

/**
 * Whether text is a legal xl identifier. xl accepts any identifier shape
 * (`point`, `MAX_DEPTH`, `$ref`); the rule rejects leading digits and
 * punctuation, which is what `E1101`/`E1203` report.
 * @param {string} text - candidate name.
 * @returns {boolean} whether the text is an identifier.
 */
export function isIdentifier(text) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(text)
}

/**
 * Split on a separator that appears outside brackets, quotes, and comments.
 *
 * A `=>` arrow is consumed as one token: its `>` is an arrow head, not a
 * generic close. Counting it would drive `depth` negative, and every later
 * separator — including the top-level commas of a parameter list — would then
 * be read as nested. That is what made a parameter list with a function-typed
 * parameter (`(predicate:(item:T)=>bool, items:Array<T>)`) unsplittable.
 * @param {string} text - input text.
 * @param {string} [sep] - single-character separator.
 * @returns {string[]} the trimmed top-level pieces.
 */
export function splitTopLevel(text, sep = ',') {
  const pieces = []
  let depth = 0
  let quote = null
  let start = 0
  for (let index = 0; index < text.length; index += 1) {
    const char = text[index]
    if (quote !== null) {
      if (char === '\\') index += 1
      else if (char === quote) quote = null
      continue
    }
    if (char === '"' || char === "'" || char === '`') {
      quote = char
      continue
    }
    if (char === '=' && text[index + 1] === '>') {
      index += 1
      continue
    }
    if (char === '(' || char === '<' || char === '[' || char === '{') depth += 1
    else if (char === ')' || char === '>' || char === ']' || char === '}') depth -= 1
    else if (char === sep && depth === 0) {
      pieces.push(text.slice(start, index).trim())
      start = index + 1
    }
  }
  pieces.push(text.slice(start).trim())
  return pieces.filter(piece => piece !== '')
}

/**
 * Index of a needle that appears at bracket/quote depth zero.
 *
 * Like {@link splitTopLevel}, a `=>` arrow is one token: its `>` must not close
 * a generic, or the depth never returns to zero and the needle is never found.
 * @param {string} text - input text.
 * @param {string} needle - text to find.
 * @returns {number} index, or -1 when absent at top level.
 */
export function indexTopLevel(text, needle) {
  let depth = 0
  let quote = null
  for (let index = 0; index < text.length; index += 1) {
    const char = text[index]
    if (quote !== null) {
      if (char === '\\') index += 1
      else if (char === quote) quote = null
      continue
    }
    if (char === '"' || char === "'" || char === '`') {
      quote = char
      continue
    }
    if (char === '=' && text[index + 1] === '>') {
      index += 1
      continue
    }
    if (char === '(' || char === '<' || char === '[' || char === '{') depth += 1
    else if (char === ')' || char === '>' || char === ']' || char === '}') depth -= 1
    else if (depth === 0 && text.startsWith(needle, index)) return index
  }
  return -1
}

/**
 * Index just past the bracket pair that opens at `start`.
 *
 * When the pair is `<…>`, a `=>` arrow inside it is one token — its `>` is an
 * arrow head and must not be taken for the closing generic bracket, or the pair
 * ends early (e.g. the constraint `T extends (a:int)=>void`).
 * @param {string} text - input text.
 * @param {number} start - index of the opening bracket.
 * @returns {number} index just past the matching close, or -1 when unbalanced.
 */
export function matchPair(text, start) {
  const open = text[start]
  const close = open === '<' ? '>' : open === '(' ? ')' : open === '[' ? ']' : '}'
  let depth = 0
  let quote = null
  for (let index = start; index < text.length; index += 1) {
    const char = text[index]
    if (quote !== null) {
      if (char === '\\') index += 1
      else if (char === quote) quote = null
      continue
    }
    if (char === '"' || char === "'" || char === '`') {
      quote = char
      continue
    }
    if (char === '=' && text[index + 1] === '>') {
      index += 1
      continue
    }
    if (char === open) depth += 1
    else if (char === close) {
      depth -= 1
      if (depth === 0) return index + 1
    }
  }
  return -1
}

/**
 * Normalize one code block for embedding (xl-emit-ts §11): LF endings, no
 * trailing whitespace, no leading or trailing blank lines, and the block's
 * own minimum indentation removed.
 * @param {string} code - raw fence body, without the fence lines.
 * @returns {string} normalized block text; empty for a blank block.
 */
export function normalizeCode(code) {
  const lines = normalizeNewlines(code)
    .split('\n')
    .map(line => line.replace(/[ \t]+$/, ''))
  while (lines.length > 0 && lines[0] === '') lines.shift()
  while (lines.length > 0 && lines[lines.length - 1] === '') lines.pop()
  if (lines.length === 0) return ''
  let base = null
  for (const line of lines) {
    if (line === '') continue
    const width = /^[ \t]*/.exec(line)[0].length
    if (base === null || width < base) base = width
  }
  const cut = base ?? 0
  return lines.map(line => (line === '' ? '' : line.slice(cut))).join('\n')
}

/**
 * Whether a normalized block contains the `yield` keyword outside strings and
 * comments; that single fact decides generator printing (xl-emit-ts §9.1).
 * @param {string} code - normalized block text.
 * @returns {boolean} whether the block yields.
 */
export function bodyHasYield(code) {
  return /\byield\b/.test(stripStringsAndComments(code))
}

/**
 * Blank out string literals, template literals, and comments so keyword scans
 * cannot match their contents. Template substitutions are blanked with their
 * literal text, which is what a keyword scan needs.
 * @param {string} code - source text.
 * @returns {string} the text with literals and comments replaced by spaces.
 */
export function stripStringsAndComments(code) {
  let out = ''
  let index = 0
  while (index < code.length) {
    const char = code[index]
    const next = code[index + 1]
    if (char === '/' && next === '/') {
      while (index < code.length && code[index] !== '\n') index += 1
      continue
    }
    if (char === '/' && next === '*') {
      index += 2
      while (index < code.length && !(code[index] === '*' && code[index + 1] === '/')) index += 1
      index += 2
      continue
    }
    if (char === '"' || char === "'" || char === '`') {
      const quote = char
      index += 1
      while (index < code.length) {
        if (code[index] === '\\') {
          index += 2
          continue
        }
        if (code[index] === quote) {
          index += 1
          break
        }
        index += 1
      }
      out += ' '
      continue
    }
    out += char
    index += 1
  }
  return out
}

/**
 * Indent every non-empty line by `level` two-space steps.
 * @param {readonly string[]} lines - lines to indent.
 * @param {number} level - indentation depth.
 * @returns {string[]} indented lines; empty lines stay empty.
 */
export function indentLines(lines, level) {
  const pad = INDENT.repeat(level)
  return lines.map(line => (line === '' ? '' : pad + line))
}

/**
 * The prose between a heading line and the next heading, with fenced code
 * removed. Used as the member's generation context and as the emptiness test
 * for `W3102`/`W3103`.
 * @param {readonly string[]} lines - the owning section's body lines.
 * @returns {string} trimmed prose, possibly empty.
 */
export function proseOf(lines) {
  const kept = []
  let fence = false
  for (const line of lines) {
    if (/^\s*```/.test(line)) {
      fence = !fence
      continue
    }
    if (fence) continue
    kept.push(line)
  }
  return kept.join('\n').trim()
}
